"""Tests for vad_engine.VADEngine.

Uses a real-speech fixture (generated by Kokoro, see
scripts/generate_test_fixtures.py) so the Silero model gets audio it can
actually recognize. Tests verify our state-tracking logic (speech
start/end timing, threshold switching, reset) rather than the model
itself, which is upstream-tested by Silero.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from voice_tutor.vad_engine import VADEngine


FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"


def _load_speech_fixture() -> np.ndarray:
    speech_path = FIXTURES_DIR / "hello_speech_16k.npy"
    if not speech_path.exists():
        pytest.skip(
            f"Speech fixture missing at {speech_path}. "
            "Run `uv run python scripts/download_models.py && "
            "uv run python scripts/generate_test_fixtures.py` to generate it."
        )
    return np.load(speech_path)


def _load_silence_fixture() -> np.ndarray:
    silence_path = FIXTURES_DIR / "silence_16k.npy"
    if not silence_path.exists():
        return np.zeros(16000 * 3, dtype=np.int16)  # 3s fallback
    return np.load(silence_path)


def _chunk_generator(audio: np.ndarray, chunk_size: int = 512):
    """Yield chunk_size-sample int16 PCM byte slices."""
    for i in range(0, len(audio) - chunk_size + 1, chunk_size):
        yield audio[i : i + chunk_size].tobytes()


# --- Construction & basic state ---

@pytest.fixture(scope="module")
def vad() -> VADEngine:
    """Module-scoped fixture — model load is ~1s, reuse across tests."""
    return VADEngine()


def test_engine_initial_state(vad: VADEngine) -> None:
    assert vad.is_speaking is False
    assert vad.silence_frames == 0


def test_chunk_samples_is_512(vad: VADEngine) -> None:
    assert vad.CHUNK_SAMPLES == 512


def test_silence_timeout_frames_computed_from_config(vad: VADEngine) -> None:
    # 500ms / 32ms-per-chunk = ~15 frames
    assert vad.silence_timeout_frames == 15


# --- Silence handling (no fixture needed) ---

def test_silent_chunk_below_threshold(vad: VADEngine) -> None:
    vad.reset()
    silence = np.zeros(512, dtype=np.int16).tobytes()
    result = vad.process_chunk(silence, agent_is_speaking=False)
    assert result["speech_prob"] < 0.6
    assert result["is_speech"] is False
    assert result["speech_ended"] is False


def test_silence_does_not_trigger_speech_ended_without_prior_speech(
    vad: VADEngine,
) -> None:
    vad.reset()
    silence = np.zeros(512, dtype=np.int16).tobytes()
    for _ in range(30):  # well past silence_timeout_frames
        result = vad.process_chunk(silence, agent_is_speaking=False)
        assert result["speech_ended"] is False


# --- Real-speech handling (fixture required) ---

def test_real_speech_triggers_is_speech(vad: VADEngine) -> None:
    """Kokoro-synthesized speech should drive VAD prob above 0.6."""
    vad.reset()
    speech = _load_speech_fixture()

    # Feed first ~1 second of speech (31 chunks of 512 samples)
    saw_speech = False
    for i, chunk in enumerate(_chunk_generator(speech)):
        if i >= 31:
            break
        result = vad.process_chunk(chunk, agent_is_speaking=False)
        if result["is_speech"]:
            saw_speech = True
            break
    assert saw_speech, "Expected Silero VAD to flag at least one chunk as speech"
    assert vad.is_speaking is True


def test_silence_after_speech_triggers_speech_ended(vad: VADEngine) -> None:
    """After speech, enough silence should produce speech_ended=True."""
    vad.reset()
    speech = _load_speech_fixture()
    silence_chunk = np.zeros(512, dtype=np.int16).tobytes()

    # First drive VAD into speaking state with ~1s of real speech
    for i, chunk in enumerate(_chunk_generator(speech)):
        if i >= 31:
            break
        vad.process_chunk(chunk, agent_is_speaking=False)
    assert vad.is_speaking is True, "Fixture speech should have triggered speaking state"

    # Now feed silence until timeout (15 frames per 500ms / 32ms)
    ended_seen = False
    for _ in range(20):
        result = vad.process_chunk(silence_chunk)
        if result["speech_ended"]:
            ended_seen = True
            break
    assert ended_seen, "Expected speech_ended after silence timeout"
    assert vad.is_speaking is False
    assert vad.silence_frames == 0


def test_real_speech_prob_above_threshold(vad: VADEngine) -> None:
    """At least one chunk in the fixture should have prob > 0.6."""
    vad.reset()
    speech = _load_speech_fixture()
    max_prob = 0.0
    for i, chunk in enumerate(_chunk_generator(speech)):
        if i >= 31:
            break
        result = vad.process_chunk(chunk, agent_is_speaking=False)
        max_prob = max(max_prob, result["speech_prob"])
    assert max_prob > 0.6, f"Max speech_prob {max_prob:.3f} should exceed 0.6"


# --- Echo-aware threshold ---

def test_barge_in_threshold_used_during_agent_speech(vad: VADEngine) -> None:
    """With agent_is_speaking=True, the engine should apply the higher 0.92
    threshold. We verify this doesn't crash and the threshold logic is wired
    up; actual echo-rejection depends on mic/speaker coupling in real use.
    """
    vad.reset()
    speech = _load_speech_fixture()
    chunk_iter = _chunk_generator(speech)
    chunk = next(chunk_iter)
    result = vad.process_chunk(chunk, agent_is_speaking=True)
    assert isinstance(result["speech_prob"], float)
    assert 0.0 <= result["speech_prob"] <= 1.0


# --- Reset behavior ---

def test_reset_clears_speech_state(vad: VADEngine) -> None:
    speech = _load_speech_fixture()
    # Drive VAD into speaking state
    for i, chunk in enumerate(_chunk_generator(speech)):
        if i >= 31:
            break
        vad.process_chunk(chunk)
    # If speech didn't trigger, force it for the test
    if not vad.is_speaking:
        vad.is_speaking = True
        vad.silence_frames = 5

    vad.reset()
    assert vad.is_speaking is False
    assert vad.silence_frames == 0


def test_reset_silence_does_not_trigger_ended(vad: VADEngine) -> None:
    """After reset, silence should NOT trigger speech_ended (no prior speech)."""
    vad.reset()
    silence = np.zeros(512, dtype=np.int16).tobytes()
    for _ in range(20):
        result = vad.process_chunk(silence)
        assert result["speech_ended"] is False


# --- Return shape ---

def test_result_has_required_keys(vad: VADEngine) -> None:
    vad.reset()
    silence = np.zeros(512, dtype=np.int16).tobytes()
    result = vad.process_chunk(silence)
    assert set(result.keys()) == {"speech_prob", "is_speech", "speech_ended"}
    assert isinstance(result["speech_prob"], float)
    assert isinstance(result["is_speech"], bool)
    assert isinstance(result["speech_ended"], bool)
    assert 0.0 <= result["speech_prob"] <= 1.0


def test_process_chunk_accepts_bytes_input(vad: VADEngine) -> None:
    """Sanity check: input is bytes, not numpy array."""
    vad.reset()
    chunk = np.zeros(512, dtype=np.int16).tobytes()
    assert isinstance(chunk, bytes)
    assert len(chunk) == 1024  # 512 samples * 2 bytes per int16
    result = vad.process_chunk(chunk)
    assert "speech_prob" in result
